[package]
name = "model"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
backend = { path = "../backend" }
config = { path = "../config" }
common = { path = "../common" }
gguf = { path = "../gguf" }
inferno-io = { package = "io", path = "../io" }
moe = { path = "../moe" }
tracing.workspace = true
